" https://github.com/junegunn/vim-plug
call plug#begin()
Plug 'wakatime/vim-wakatime'
Plug 'dracula/vim', { 'as': 'dracula' }
call plug#end()

let g:dracula_colorterm = 0
colorscheme dracula

highlight NonText ctermfg=12
