# Enviroment vars
export EDITOR=vim
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="gallois"
export WORKON_HOME=$HOME/.virtualenvs

# Autocompleat
autoload -U compinit promptinit
compinit
promptinit; prompt gentoo

# Oh my zsh
source $ZSH/oh-my-zsh.sh

# Aliases
alias k='kubectl'
alias ls="ls --color -l -h" 
alias ll="ls --color -l -h -a" 
alias mkdir="mkdir -pv"
alias grep="grep -n --color"
alias neofetch="fastfetch"
alias copy='f(){ cat "$@" | wl-copy ;  unset -f f; }; f'

alias idea="~/.local/share/JetBrains/Toolbox/scripts/idea1 &"

## Fix special stuff
bindkey  "^[[H"    beginning-of-line
bindkey  "^[[F"    end-of-line
bindkey  "^[[3~"   delete-char
bindkey "^H" backward-kill-word
bindkey  "^[[3;5~" kill-word
bindkey  "^[[1;5C" forward-word
bindkey  "^[[1;5D" backward-word

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

plugins=(
	virtualenvwrapper
)

# Path
export PATH="$PATH:$(yarn global bin)"
export PATH=$HOME/.local/bin:$PATH

