
[window]

opacity = 0.8

padding.x = 3
padding.y = 3

decorations = "Full"

[font]
size = 10.0
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

[general]
import = ["~/.config/alacritty/dracula.toml"]
